[package]
name = "seventeen"
version = "0.1.0"
edition = "2021"

[dependencies]
rayon = "1.10.0"

[[bin]]
name = "seventeen"
path = "main.rs"

[profile.release]
lto = true
panic = "abort"
codegen-units = 1
